# GitHub Action: https://dev.to/leoloso/using-github-actions-to-release-a-wordpress-plugin-42a5

name: Generate Installable Plugin, and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          composer install --no-dev --optimize-autoloader
          mkdir build
      - name: Create artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r build/wooms.zip . -x *.git* node_modules/\* .* "*/\.*" CODE_OF_CONDUCT.md CONTRIBUTING.md ISSUE_TEMPLATE.md PULL_REQUEST_TEMPLATE.md *.dist composer.* dev-helpers** build** vendor/\* docs/\*
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: wooms
            path: build/wooms.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: build/wooms.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
